### ISSUE TITLE
import pacparser fails in both python 3.12 and 3.11

### ISSUE THREAD

**Issue by pexarkh** [manugarg/pacparser#196]
i've installed the latest pacparser:

```
> pip install pacparser
Collecting pacparser
  Downloading pacparser-1.4.3-cp312-cp312-macosx_10_9_universal2.whl.metadata (250 bytes)
Downloading pacparser-1.4.3-cp312-cp312-macosx_10_9_universal2.whl (459 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 459.1/459.1 kB 2.3 MB/s eta 0:00:00
Installing collected packages: pacparser
Successfully installed pacparser-1.4.3
```

but it fails immediately while being imported with

<i>ImportError: dlopen(/Users/wrp/py3envs/pacparser-test/lib/python3.12/site-packages/pacparser/_pacparser.cpython-312-darwin.so, 0x0002): tried: '/Users/wrp/py3envs/pacparser-test/lib/python3.12/site-packages/pacparser/_pacparser.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))</i>

because maybe it shouldn't be .so but .dylib on mac?

full output for python 3.12:

```
> python3
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pacparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wrp/py3envs/pacparser-test/lib/python3.12/site-packages/pacparser/__init__.py", line 31, in <module>
    from pacparser import _pacparser
ImportError: dlopen(/Users/wrp/py3envs/pacparser-test/lib/python3.12/site-packages/pacparser/_pacparser.cpython-312-darwin.so, 0x0002): tried: '/Users/wrp/py3envs/pacparser-test/lib/python3.12/site-packages/pacparser/_pacparser.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/wrp/py3envs/pacparser-test/lib/python3.12/site-packages/pacparser/_pacparser.cpython-312-darwin.so' (no such file), '/Users/wrp/py3envs/pacparser-test/lib/python3.12/site-packages/pacparser/_pacparser.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

full output for python 3.11:

```
> python3
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pacparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wrp/projects/manugarg--pacparser_git/py311venv/lib/python3.11/site-packages/pacparser/__init__.py", line 31, in <module>
    from pacparser import _pacparser
ImportError: dlopen(/Users/wrp/projects/manugarg--pacparser_git/py311venv/lib/python3.11/site-packages/pacparser/_pacparser.cpython-311-darwin.so, 0x0002): tried: '/Users/wrp/projects/manugarg--pacparser_git/py311venv/lib/python3.11/site-packages/pacparser/_pacparser.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/wrp/projects/manugarg--pacparser_git/py311venv/lib/python3.11/site-packages/pacparser/_pacparser.cpython-311-darwin.so' (no such file), '/Users/wrp/projects/manugarg--pacparser_git/py311venv/lib/python3.11/site-packages/pacparser/_pacparser.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

please kindly help. thank you.

**Comment by manugarg** [comment]
It's due to architecture difference. We currently don't have pre-built binaries for arm64.

**Comment by manugarg** [comment]
This should be fixed now.
